image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push
  - test

before_script:
  - docker info

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - sh docker-build.sh
    - docker images

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
   # put the build commands in this script instead of messing with the yaml nesting mess >
   # https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
   - sh docker-build.sh
   - docker images
   # there's no way in hell I'm going to push one by one by hand
   - for tag in "$(grep "\-\t" docker-build.sh | awk '{print $2}')";do docker push "${tag}";done

test_docker_images:
  stage: test
  only:
   - master
  script:
    # dockerhub
    - for tag in "$(grep "\-\t" docker-build.sh | awk '{print $2}')";do docker run --rm "${tag}" cat /etc/os-release;done
