image: docker:20.10

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10-dind

stages:
  - build
  - push

before_script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - sh docker-build.sh

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - sh docker-push.sh
