---
services: docker

env:
  global:
    - DOCKER_USER: qwe1
    - DOCKER_IMAGE: docker-debian
  #matrix:
  #  - whatever

before_script:
  - docker info

script:
  # Run tests.
  - docker build -t $DOCKER_USER/$DOCKER_IMAGE:travis-$DOCKER_IMAGE .
  - docker images
  - docker run --rm $DOCKER_USER/$DOCKER_IMAGE:travis-$DOCKER_IMAGE cat /etc/os-release
  - docker run --rm $DOCKER_USER/$DOCKER_IMAGE:stretch-nonfree cat /etc/apt/sources.list
  - docker run --rm $DOCKER_USER/$DOCKER_IMAGE:buster-nonfree cat /etc/apt/sources.list
