FROM debian:stretch-slim
RUN apt-get update && \
    apt-get install -y python sudo bash ca-certificates lsb-release && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* && \
    apt-get clean