FROM debian:bookworm-slim

# seems Bookworm(D12) ct images come with debian.sources
# files in /etc/apt/sources.list.d
# whereas manual installations have the old /etc/apt/sources.list files
RUN rm -f /etc/apt/sources.list.d/debian.sources

COPY extras/d12-sources.list /etc/apt/sources.list

COPY extras/d12-no-bookworm-firmware.conf /etc/apt/apt.conf.d/no-bookworm-firmware.conf

RUN apt-get update && \
    apt-get install --no-install-recommends -y wget curl git ca-certificates && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /var/tmp/* && \
    apt-get clean
