FROM qwe1/docker-debian:10-nonfree
RUN apt-get update && \
    apt-get install -y python sudo bash ca-certificates lsb-release && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* && \
    apt-get clean