FROM debian:buster-slim

RUN apt-get update && \
    apt-get install -y python sudo bash ca-certificates lsb-release systemd && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* && \
    apt-get clean

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]